import { StyleSheet } from 'react-native';
import { C, sharedStyles, S, R, F, W, T, M } from '../theme';

export default { ...sharedStyles, ...StyleSheet.create({
  statsCard: { backgroundColor: C.paper, borderRadius: R.card, padding: S.lg, borderWidth: M.n1, borderColor: C.line, marginBottom: S.md },
  accuracyRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: S.md },
  accuracySide: { flex: 1, alignItems: 'center' },
  accuracyValue: { color: C.ink, fontSize: F.title, fontWeight: W.semibold, letterSpacing: M.zero },
  accuracyLabel: { color: C.muted, fontSize: F.secondary, fontWeight: W.semibold, marginTop: S.xs },
  accuracyDivider: { width: M.n1, height: M.n38, backgroundColor: C.line },
  countRow: { borderTopWidth: M.n1, borderTopColor: C.line, paddingTop: S.md, gap: S.sm },
  countItem: { flexDirection: 'row', alignItems: 'center', minHeight: M.n19 },
  countDot: { width: M.n7, height: M.n7, borderRadius: R.small, marginRight: S.sm },
  countText: { color: C.muted, fontSize: F.secondary, flex: 1, textTransform: 'capitalize' },
  countNumber: { color: C.ink, fontSize: F.secondary, fontWeight: W.semibold },
  countLegend: { color: C.faint, fontSize: F.secondary, textAlign: 'right', marginTop: S.xs },
  graphWrap: { backgroundColor: C.paper, borderWidth: M.n1, borderColor: C.line, borderRadius: R.card, padding: S.md, marginBottom: S.md, overflow: 'hidden' },
  graphLabels: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: S.xs },
  graphHint: { color: C.faint, fontSize: F.secondary },
  graphAxis: { flexDirection: 'row', justifyContent: 'space-between', paddingTop: S.xs },
  boardCard: { backgroundColor: C.paper, borderWidth: M.n1, borderColor: C.line, borderRadius: R.card, padding: S.md, marginBottom: S.md },
  boardHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: S.sm, gap: S.sm },
  boardTitle: { color: C.ink, fontWeight: W.semibold, fontSize: F.secondary },
  boardEval: { color: C.muted, fontSize: F.secondary, flexShrink: 1, textAlign: 'right' },
  stepRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: S.sm },
  stepButton: { minHeight: M.n48, minWidth: M.n48, justifyContent: 'center', paddingVertical: S.sm, paddingHorizontal: S.sm, borderRadius: R.small, backgroundColor: C.greenSoft },
  stepText: { color: C.ink, fontWeight: W.semibold, fontSize: F.secondary },
  plyText: { color: C.muted, fontSize: F.secondary },
  bestMoveNote: { color: C.muted, fontSize: F.secondary, textAlign: 'left', marginTop: S.sm },
  reviewLegend: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: S.sm, marginTop: S.xs, marginBottom: S.xs },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: S.xs },
  legendDot: { width: M.n7, height: M.n7, borderRadius: R.small },
  legendLabel: { color: C.muted, fontSize: F.secondary, fontWeight: W.semibold },
  movesCard: { backgroundColor: C.paper, borderWidth: M.n1, borderColor: C.line, borderRadius: R.card, padding: S.md, marginBottom: S.lg },
  sectionTitle: { color: C.ink, fontWeight: W.semibold, fontSize: F.body, letterSpacing: M.zero },
  moveGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: S.sm },
  moveChip: { minHeight: M.n48, minWidth: M.n44, flexDirection: 'row', alignItems: 'center', paddingVertical: S.xs, paddingHorizontal: S.xs, borderRadius: R.small },
  moveChipActive: { backgroundColor: C.greenSoft },
  moveNumber: { color: C.faint, fontSize: F.secondary, minWidth: M.n17 },
  moveSan: { fontSize: F.secondary, fontWeight: W.semibold },
  criticalSection: { marginBottom: S.lg },
  sectionCopy: { color: C.muted, fontSize: F.secondary, lineHeight: T.body, marginTop: S.xs, marginBottom: S.sm },
  criticalCard: { backgroundColor: C.paper, borderWidth: M.n1, borderColor: C.line, borderRadius: R.card, padding: S.md, marginBottom: S.sm },
  criticalTop: { flexDirection: 'row', alignItems: 'center', gap: S.md, marginBottom: S.md },
  miniBoard: { width: M.n76, height: M.n76, borderRadius: R.small, overflow: 'hidden' },
  criticalDetails: { flex: 1, alignItems: 'flex-start' },
  criticalPlayed: { color: C.ink, fontSize: F.secondary, fontWeight: W.semibold, marginTop: S.sm },
  criticalBest: { color: C.ink, fontSize: F.secondary, marginTop: S.xs },
  criticalLoss: { color: C.red, fontSize: F.secondary, fontWeight: W.semibold, marginTop: S.xs },
  phaseTag: { color: C.faint, fontSize: F.secondary, fontWeight: W.semibold, letterSpacing: M.zero, marginTop: S.xs },
  noticeCard: { backgroundColor: C.paper, borderWidth: M.n1, borderColor: C.line, borderRadius: R.card, padding: S.md },
  noticeCopy: { color: C.muted, fontSize: F.secondary, lineHeight: T.body },
  progressTrack: { height: M.n6, backgroundColor: C.soft, borderRadius: R.small, overflow: 'hidden', width: '100%', marginTop: S.lg },
  progressFill: { height: '100%', backgroundColor: C.green },
  loadingCard: { alignItems: 'center', paddingVertical: S.lg },
  card: { backgroundColor: C.paper, borderRadius: R.card, padding: S.lg, borderWidth: M.n1, borderColor: C.line, marginBottom: S.lg },
  cardTitle: { color: C.ink, fontSize: F.body, fontWeight: W.semibold, marginTop: S.md, textAlign: 'left' },
  cardCopy: { color: C.muted, fontSize: F.secondary, lineHeight: T.body, marginTop: S.sm, marginBottom: S.sm, textAlign: 'left' },
  coachCard: { backgroundColor: C.paper, borderRadius: R.card, padding: S.md, marginTop: S.xs, marginBottom: S.md, borderWidth: M.n1, borderColor: C.line },
  coachHead: { flexDirection: 'row', alignItems: 'center' },
  coachTitle: { color: C.ink, fontSize: F.secondary, fontWeight: W.semibold },
  coachCopy: { color: C.muted, fontSize: F.secondary, lineHeight: T.body, marginTop: S.xs },
  coachMark: { color: C.muted, fontSize: F.section, marginLeft: S.sm },
  coachSummary: { color: C.ink, fontSize: F.secondary, lineHeight: T.body, marginTop: S.md },
  coachPhase: { color: C.muted, fontSize: F.secondary, lineHeight: T.body, marginTop: S.sm },
  errorText: { color: C.red, fontSize: F.secondary, marginBottom: S.sm },
}) };
