import { StyleSheet } from 'react-native';
import { C, sharedStyles, S, R, F, W, T, M } from '../theme';

export default { ...sharedStyles, ...StyleSheet.create({
  container: { flex: 1 },
  boardWrap: { paddingTop: S.xs, marginBottom: S.md },
  demoTools: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: S.xs, marginTop: S.xs },
  demoCount: { color: C.faint, fontSize: F.secondary, fontWeight: W.semibold, letterSpacing: M.zero },
  replayButton: { minHeight: M.n48, justifyContent: 'center', paddingVertical: S.xs, paddingHorizontal: S.sm, borderRadius: R.small, backgroundColor: C.greenSoft },
  replayText: { color: C.ink, fontSize: F.secondary, fontWeight: W.semibold },
  captionCard: { padding: S.lg, backgroundColor: C.paper, borderWidth: M.n1, borderColor: C.line, borderRadius: R.card },
  captionTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  stepType: { color: C.faint, fontSize: F.secondary, fontWeight: W.semibold, letterSpacing: M.zero },
  captionTitle: { color: C.ink, fontSize: F.body, fontWeight: W.semibold, lineHeight: T.body, letterSpacing: M.zero, marginTop: S.md },
  helperText: { color: C.muted, fontSize: F.body, lineHeight: T.body, marginTop: S.md },
  inlineActions: { flexDirection: 'row', alignItems: 'center', gap: S.sm, marginTop: S.sm },
  answerText: { color: C.ink, fontSize: F.secondary, fontWeight: W.semibold, flexShrink: 1 },
  options: { gap: S.sm, marginTop: S.md },
  option: { minHeight: M.n48, justifyContent: 'center', padding: S.md, borderWidth: M.n1, borderColor: C.line, borderRadius: R.small, backgroundColor: C.white },
  optionChosen: { borderColor: C.amber, backgroundColor: C.amberSoft },
  optionCorrect: { borderColor: C.green, backgroundColor: C.greenSoft },
  optionText: { color: C.ink, fontSize: F.secondary, fontWeight: W.semibold },
  feedback: { backgroundColor: C.amberSoft, borderRadius: R.small, padding: S.md, marginTop: S.md },
  feedbackSuccess: { backgroundColor: C.greenSoft },
  feedbackText: { color: C.ink, fontSize: F.secondary, lineHeight: T.body },
  progressDots: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: S.sm, marginTop: S.md, marginBottom: S.sm },
  dot: { height: M.n6, width: M.n6, borderRadius: R.small, backgroundColor: C.muted },
  dotActive: { width: M.n19, borderRadius: R.small, backgroundColor: C.amber },
  dotDone: { backgroundColor: C.green },
  bottomAction: { marginTop: 'auto', paddingTop: S.sm, paddingBottom: S.xs },
}) };
