export const C = {
  bg: '#f6f5f0',
  paper: '#ffffff',
  ink: '#1d211b',
  muted: '#787d73',
  faint: '#a2a59c',
  line: '#e9e8e1',
  soft: '#eeeee8',
  green: '#243b2c',
  green2: '#354c38',
  amber: '#c88927',
  amberSoft: '#f6ebd8',
  greenSoft: '#e9efe6',
  boardLight: '#f0eee2',
  boardDark: '#83927b',
  red: '#b54d43',
  white: '#fffdf3'
};

export const PIECE_NAMES = {
  k: 'king',
  q: 'queen',
  r: 'rook',
  b: 'bishop',
  n: 'knight',
  p: 'pawn'
};

import { StyleSheet } from 'react-native';

export const sharedStyles = StyleSheet.create({
  pressed:{opacity:0.76},
  sectionHead:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',marginTop:7,marginBottom:11,gap:8},
  eyebrow:{color:C.muted,fontSize:9,fontWeight:'800',letterSpacing:1.05,marginBottom:5},
  sectionTitle:{color:C.ink,fontSize:20,fontWeight:'700',letterSpacing:-0.65},
  bodyMuted:{color:C.muted,fontSize:12,lineHeight:18,marginTop:4},
  resultDot:{height:8,width:8,borderRadius:4},
  rowTitle:{color:C.ink,fontWeight:'700',fontSize:12},
  rowSub:{color:C.muted,fontSize:9,marginTop:4},
  resultText:{fontSize:10,fontWeight:'700'},
  rowChevron:{color:C.faint,fontSize:20,marginLeft:1},
  page:{paddingHorizontal:20,paddingTop:13,paddingBottom:24},
  hero:{minHeight:240,borderRadius:19,padding:20,backgroundColor:C.green,overflow:'hidden',marginBottom:15},
  heroTitle:{color:'#fffdf6',fontSize:35,lineHeight:38,letterSpacing:-1.5,fontWeight:'700',marginTop:22},
  heroSub:{color:'#e0e5da',fontSize:13,lineHeight:19,marginTop:10,maxWidth:255},
  card:{backgroundColor:C.paper,borderRadius:16,padding:17,borderWidth:1,borderColor:C.line,marginBottom:22},
  cardTitle:{color:C.ink,fontSize:19,fontWeight:'700',letterSpacing:-0.4,marginTop:13},
  cardCopy:{color:C.muted,fontSize:12,lineHeight:18,marginTop:6},
  input:{height:46,borderWidth:1,borderColor:'#e3e4dc',borderRadius:10,paddingHorizontal:13,color:C.ink,fontSize:14,backgroundColor:'#fcfcfa',marginBottom:10},
  errorText:{color:C.red,fontSize:12,lineHeight:17,marginBottom:10,marginTop:7},
  privacyNote:{textAlign:'center',marginTop:10,fontSize:10,color:C.faint},
  stat:{flex:1,alignItems:'center'},
  statValue:{color:C.green,fontSize:20,fontWeight:'700'},
  statLabel:{color:C.muted,fontSize:8,fontWeight:'700',letterSpacing:0.65,marginTop:2},
  statDivider:{width:1,height:31,backgroundColor:C.line},
  focusCard:{flexDirection:'row',alignItems:'center',gap:11,padding:13,backgroundColor:C.paper,borderWidth:1,borderColor:C.line,borderRadius:13,marginBottom:22},
  focusIcon:{height:39,width:39,borderRadius:13,backgroundColor:C.amberSoft,alignItems:'center',justifyContent:'center'},
  focusIconText:{color:C.amber,fontSize:20},
  focusTitle:{fontSize:13,color:C.ink,fontWeight:'700'},
  focusCopy:{fontSize:10,color:C.muted,marginTop:3,lineHeight:14,flexShrink:1},
  roundArrow:{width:30,height:30,borderRadius:15,backgroundColor:C.green,alignItems:'center',justifyContent:'center'},
  roundArrowText:{color:'#fff',fontSize:16,marginTop:-1},
  linkText:{color:C.green,fontSize:11,fontWeight:'700',paddingVertical:4},
  smallEmpty:{paddingVertical:17,paddingHorizontal:13,backgroundColor:C.paper,borderRadius:11,borderWidth:1,borderColor:C.line},
  smallEmptyText:{color:C.muted,fontSize:12,lineHeight:17},
  bottomSpace:{height:12},
  pageIntro:{marginTop:9,marginBottom:19},
  pageTitle:{color:C.ink,fontSize:31,lineHeight:37,letterSpacing:-1.3,fontWeight:'700',marginTop:10},
  pageSubtitle:{color:C.muted,fontSize:13,lineHeight:19,marginTop:5},
  insightCard:{minHeight:174,borderRadius:16,padding:17,backgroundColor:C.green,marginBottom:15,overflow:'hidden'},
  eyebrowLight:{color:'#c5d1bf',fontSize:9,fontWeight:'800',letterSpacing:1},
  insightTitle:{color:'#fffdf6',fontSize:24,lineHeight:27,letterSpacing:-0.6,fontWeight:'700',marginTop:13},
  insightCopy:{color:'#d3ddce',fontSize:11,lineHeight:16,maxWidth:230,marginTop:7},
  insightMark:{position:'absolute',right:13,bottom:5,fontSize:71,color:'#c8a767',opacity:0.43},
  noticeCard:{flexDirection:'row',alignItems:'flex-start',gap:10,backgroundColor:'#f0f1eb',padding:13,borderRadius:12,borderWidth:1,borderColor:C.line},
  noticeIcon:{fontSize:20,color:C.amber,width:22,textAlign:'center'},
  noticeTitle:{fontSize:11,fontWeight:'700',color:C.ink},
  noticeCopy:{color:C.muted,fontSize:10,lineHeight:15,marginTop:3},
  backButton:{alignSelf:'flex-start',paddingVertical:4,paddingRight:12,marginBottom:8},
  backText:{color:C.green,fontWeight:'700',fontSize:13},
  modeSwitch:{flexDirection:'row',padding:4,backgroundColor:'#eaeae4',borderRadius:11,marginBottom:13},
  modeOption:{flex:1,alignItems:'center',paddingVertical:9,borderRadius:8},
  modeOptionActive:{backgroundColor:C.paper,shadowColor:'#182018',shadowOpacity:0.07,shadowRadius:5,elevation:1},
  modeText:{color:C.muted,fontSize:11,fontWeight:'600'},
  modeTextActive:{color:C.green,fontWeight:'800'},
  pathCard:{flexDirection:'row',alignItems:'center',gap:11,minHeight:70,padding:12,marginBottom:9,borderRadius:12,backgroundColor:C.paper,borderWidth:1,borderColor:C.line},
  pathNumber:{width:34,height:34,borderRadius:12,backgroundColor:C.amberSoft,alignItems:'center',justifyContent:'center'},
  pathNumberText:{color:'#8b6324',fontSize:10,fontWeight:'800'},
  setupChoice:{padding:13,borderWidth:1,borderColor:C.line,backgroundColor:'#fbfbf8',borderRadius:11,marginTop:7},
  setupChoiceActive:{borderColor:C.green,backgroundColor:C.greenSoft}
});
